### ISSUE TITLE
CustomEvent error using solid-start

### ISSUE THREAD

**Issue by davedbase** [otonashixav/solid-flip#7]
I'm trying to use solid-flip in a solid-start powered codebase. I keep receiving the error:
```
Error when evaluating SSR module /src/routes/index.tsx:
ReferenceError: CustomEvent is not defined
    at file:///Users/ddibiase/Projects/test/node_modules/@otonashixav/solid-flip/dist/esm/index.js:192:40
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async nodeImport (/Users/ddibiase/Projects/test/node_modules/vite/dist/node/chunks/dep-f5552faa.js:60169:21)
    at async eval (/src/routes/index.tsx:22:31)
    at async instantiateModule (/Users/ddibiase/Projects/test/node_modules/vite/dist/node/chunks/dep-f5552faa.js:60105:9)
```

**Comment by otonashixav** [comment]
Fixed in 0.10.5
